table Tabla_de_Medidas
	lineageTag: fdc3b00a-51d0-4ea8-abe5-26eb6212a69e

	measure 'Total Beneficios' = SUM('Registros_2020-2022'[Ingresos])-SUM('Registros_2020-2022'[Gastos])
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 438d67c4-1ecd-4b3f-8f4d-06ce92fa61cf

	measure Margen = Tabla_de_Medidas[Total Beneficios]/ SUM('Registros_2020-2022'[Ingresos])
		formatString: 0.000\ %;-0.000\ %;0.000\ %
		lineageTag: 1abf187e-af03-4670-8373-fc5031659f9c

	measure 'Margen 2' = DIVIDE(Tabla_de_Medidas[Total Beneficios],SUM('Registros_2020-2022'[Ingresos]),0)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 691450c0-681e-4a2d-be27-1750d3cafe39

	partition Tabla_de_Medidas = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

